/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bak;

import javax.swing.JOptionPane;

/**
 *
 * @author Dafa Zakhulhaq
 */
public class tarik extends javax.swing.JFrame {

    
        int tabungan,teks2 ;
        String teks1 ;
        public int tarik1 ;
        
    
    /**
     * Creates new form tarik
     */
    public tarik() {
        initComponents();
        
        
        home tarik = new home() ;
        tabungan = tarik.getsaldo() ;
        
        saldo.setText(""+tabungan);
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        saldo = new javax.swing.JLabel();
        tj1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btarik = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Rp.");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 130, 40, 60);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Penarikan Tunai");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 10, 210, 60);

        saldo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        saldo.setForeground(new java.awt.Color(255, 255, 255));
        saldo.setText("0");
        jPanel1.add(saldo);
        saldo.setBounds(80, 130, 120, 60);

        tj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tj1ActionPerformed(evt);
            }
        });
        jPanel1.add(tj1);
        tj1.setBounds(190, 90, 170, 60);

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(190, 250, 170, 40);

        btarik.setText("Tarik");
        btarik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btarikActionPerformed(evt);
            }
        });
        jPanel1.add(btarik);
        btarik.setBounds(190, 160, 170, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 300);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void tj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tj1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tj1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
      this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btarikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btarikActionPerformed
        // TODO add your handling code here:
        
        teks1 = tj1.getText() ;
        teks2 = Integer.parseInt(teks1) ;
        
        if(teks2 < 50000){
            
            JOptionPane.showMessageDialog(null, " Uang yang anda tarik kurang dari 50000");
            
        }else{
            
            
             tarik1 = tabungan - teks2 ;
             JOptionPane.showMessageDialog(null, " Penarikan Anda Berhasil");
       
        
            
             saldo.setText(""+tarik1);
            
        }
        
    }//GEN-LAST:event_btarikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tarik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tarik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tarik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tarik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tarik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btarik;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel saldo;
    private javax.swing.JTextField tj1;
    // End of variables declaration//GEN-END:variables
}
