/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bak;

import javax.swing.JOptionPane;

/**
 *
 * @author Dafa Zakhulhaq
 */
public class transfer extends javax.swing.JFrame {

    
        int tabungan,teks2,teks2a ;
        String teks1,teks1a ;
        public int tarik1 ;
        
    
    /**
     * Creates new form tarik
     */
    public transfer() {
        initComponents();
        
        
        home tarik = new home() ;
        tabungan = tarik.getsaldo() ;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tj1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btarik = new javax.swing.JButton();
        tj2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Rp.");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(190, 160, 40, 60);

        tj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tj1ActionPerformed(evt);
            }
        });
        jPanel1.add(tj1);
        tj1.setBounds(240, 160, 120, 60);

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(190, 250, 170, 40);

        btarik.setText("Transfer");
        btarik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btarikActionPerformed(evt);
            }
        });
        jPanel1.add(btarik);
        btarik.setBounds(10, 250, 170, 40);

        tj2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tj2ActionPerformed(evt);
            }
        });
        jPanel1.add(tj2);
        tj2.setBounds(190, 80, 170, 60);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Transfer Tunai");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 10, 210, 60);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nomor Rekening");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 80, 210, 60);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tunai");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 160, 210, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 300);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
      this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btarikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btarikActionPerformed
        // TODO add your handling code here:
        
        teks1 = tj1.getText() ;
        teks1a = tj2.getText() ;

        teks2 = Integer.parseInt(teks1) ;
        teks2a = Integer.parseInt(teks1a) ;
        
    
        if(teks1a.length() == 8)
        {
        if(teks2 < 50000){
            
            JOptionPane.showMessageDialog(null, " Uang yang anda transfer kurang dari 50000");
            
        }else{
            
            
             tarik1 = tabungan - teks2 ;
             JOptionPane.showMessageDialog(null, " Transfer Anda Berhasil");
        }
        }else if(teks1a.length() != 8){
            
            JOptionPane.showMessageDialog(null, " Karakter Harus Berjumlah 8");
        }
        
    }//GEN-LAST:event_btarikActionPerformed

    private void tj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tj1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tj1ActionPerformed

    private void tj2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tj2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tj2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btarik;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tj1;
    private javax.swing.JTextField tj2;
    // End of variables declaration//GEN-END:variables
}
